### ISSUE TITLE
Cannot install pkg

### ISSUE THREAD

**Issue by icankeep** [jupyterlab-contrib/search-replace#1]
can not find pkg in pypi

![image](https://user-images.githubusercontent.com/39434627/147450501-c731cd49-972f-411c-826a-96134c5b11b6.png)

**Comment by icankeep** [comment]
![image](https://user-images.githubusercontent.com/39434627/147450607-05dbfdc9-f598-49be-8e0f-63487b66af57.png)

**Comment by fcollonval** [comment]
@icankeep a first early version has been published - more developments are in progress.
